version: '3.3'
services:
  interface:
    build: ../GeneratorSensorGateringInterface
    restart: always
    ports:
      - '443:443'
  server:
    build: ../GeneratorSensorGateringServer
    restart: always
    ports:
      - '59595:59595'
    extra_hosts:
      - 'localhost:10.0.4.2'
